# Generated by Django 5.0.4 on 2024-04-04 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Author', models.CharField(max_length=255)),
                ('Key_features', models.CharField(max_length=255)),
                ('Banner', models.ImageField(upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='LMSAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Channel', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('info_LMS', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=255)),
                ('Created_date', models.DateField()),
                ('Product_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Document', models.CharField(max_length=255)),
                ('Terms_and_conditions', models.CharField(max_length=855)),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidata.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='LMSAccesss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidata.lmsaccess'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Refrencecourse', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=255)),
                ('Summary_of_Resource', models.CharField(max_length=255)),
                ('Banner', models.ImageField(upload_to='banners/')),
                ('Type', models.CharField(max_length=255)),
                ('Component', models.CharField(max_length=255)),
                ('subadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidata.subadmin')),
            ],
        ),
        migrations.CreateModel(
            name='onlineClasses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_info', models.TextField()),
                ('training_info', models.TextField()),
                ('channel', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('trainer', models.CharField(max_length=100)),
                ('landing_page', models.URLField()),
                ('Location', models.CharField(max_length=100)),
                ('Schedule', models.CharField(max_length=100)),
                ('LMSAccesss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidata.lmsaccess')),
                ('subadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidata.subadmin')),
            ],
        ),
        migrations.CreateModel(
            name='LMSCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=255)),
                ('Value', models.CharField(max_length=255)),
                ('Publication', models.CharField(max_length=255)),
                ('subadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidata.subadmin')),
            ],
        ),
        migrations.AddField(
            model_name='lmsaccess',
            name='subadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidata.subadmin'),
        ),
        migrations.AddField(
            model_name='course',
            name='subadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidata.subadmin'),
        ),
    ]
